version: '3.4'

services:

  sshd:
    build:
      context: .
      dockerfile: Dockerfile-sshd
    image: fluidog/sshd
    restart: unless-stopped
    network_mode: host
    privileged : true
    tmpfs:
      - /run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
      - /root/workspace:/root/workspace

  samba:
    profiles:
      - samba
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    environment:
      USERID: 0
      GROUPID: 0
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - /root/workspace:/root/workspace
    command: '
      -s "workspace;/root/workspace;;no"
      -g "create mask = 0644" -g "force create mode = 0" 
      -g "directory mask = 0755" -g "force directory mode = 0"
      '

  nfs-server:
    profiles:
      - nfs-server
    image: gists/nfs-server
    ports:
      - "2049:2049"
    environment:
      NFS_OPTION: "fsid=root,rw,sync,insecure,all_squash,anonuid=0,anongid=0,no_subtree_check"
    privileged: true
    volumes:
      - /root/workspace/:/nfs-share
  

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.67.0.0/16"
